-- ZADANIE 1
CREATE DATABASE demoDB
	ON
		(NAME = demoDB1,
		 FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\demoDB1.mdf',
		 SIZE = 3072KB, FILEGROWTH = 1024KB)
	LOG ON 
		(NAME = demoDB1_log,
		 FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\demoDB1_log.ldf',
		 SIZE = 5120KB, FILEGROWTH = 10%);

-- ZADANIE 2
ALTER DATABASE demoDB
	ADD FILEGROUP FG1;

-- ZADANIE 3
ALTER DATABASE demoDB
	ADD FILE (NAME = demoDB,
			  FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\demoDB.ndf',
			  SIZE = 5120KB, FILEGROWTH = 1024KB)
			  TO FILEGROUP FG1;

-- ZADANIE 4
ALTER DATABASE demoDB
MODIFY FILEGROUP FG1
DEFAULT;

-- ZADANIE 5
CREATE TABLE tab1(
	id int IDENTITY(1,1) CONSTRAINT PK_tab1_id PRIMARY KEY,
	tekst char(200));

-- ZADANIE 6
WHILE(1 > 0)
BEGIN INSERT INTO tab1 (tekst) VALUES ('RANDOM TEXT') CONTINUE;
END;

SELECT * FROM tab1;

-- ZADANIE 7
ALTER DATABASE demoDB
	ADD FILE (NAME = demoDB2,
			  FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\demoDB2.ndf',
			  SIZE = 5120KB, FILEGROWTH = 1024KB)
			  TO FILEGROUP [PRIMARY];
			  
-- ZADANIE 8
CREATE TABLE tab2(
	id int IDENTITY(1,1) CONSTRAINT PK_tab2_id PRIMARY KEY,
	tekst char(200))
	ON [PRIMARY];
	
-- ZADANIE 9
WHILE(1 > 0)
BEGIN INSERT INTO tab2 (tekst) VALUES ('RANDOM TEXT') CONTINUE;
END;

SELECT * FROM tab2;

-- ZADANIE 10
--OK

CREATE TABLE tab3(
	id int IDENTITY(1,1) CONSTRAINT PK_tab3_id PRIMARY KEY,
	tekst varchar(50));
	
INSERT INTO tab3 (tekst) VALUES ('abc'),('AbC'),('aBc');
----
SELECT * FROM tab3 
WHERE tekst ='abc';

SELECT * FROM tab3 
WHERE tekst COLLATE Polish_CS_AS = 'abc';
---
INSERT INTO tab3 VALUES('cAb'),('baZ');

SELECT tekst FROM tab3
ORDER BY tekst;

SELECT tekst FROM tab3
ORDER BY tekst COLLATE Polish_CS_AS;
--
INSERT INTO tab3 VALUES('¹æŸ'),('êæ¿'),('exy'),('êqa');

SELECT * FROM tab3 ORDER BY tekst --(CI_AS)
SELECT tekst FROM tab3 ORDER BY tekst COLLATE Polish_CI_AI --(CI_AI)

SELECT * FROM tab3 ORDER BY tekst --(CI_AS)
SELECT tekst FROM tab3 ORDER BY tekst COLLATE Polish_CS_AI --(CS_AI)

-- ZADANIE 11
ALTER DATABASE demoDB
	SET PAGE_VERIFY CHECKSUM;
	
-- ZADANIE 12
ALTER DATABASE demoDB SET OFFLINE WITH ROLLBACK IMMEDIATE;

USE master
go
select * from demodb.dbo.tab1;

-- ZADANIE 13
ALTER DATABASE demoDB SET ONLINE WITH ROLLBACK IMMEDIATE;

-- ZADANIE 14
ALTER DATABASE demoDB SET READ_ONLY WITH ROLLBACK IMMEDIATE;

alter table tab1  add nazwisko  varchar ( 40 )

-- ZADANIE 15
ALTER DATABASE demoDB SET READ_WRITE WITH ROLLBACK IMMEDIATE;

-- ZADANIE 16
ALTER DATABASE demoDB SET SINGLE_USER WITH ROLLBACK IMMEDIATE;

-- ZADANIE 17
ALTER DATABASE demoDB SET RESTRICTED_USER WITH ROLLBACK IMMEDIATE;